# Generated by Django 4.2 on 2023-05-01 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='MENU',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=255)),
                ('lastname', models.CharField(max_length=255)),
                ('phone', models.IntegerField(null=True)),
                ('joined_date', models.DateField(null=True)),
            ],
        ),
    ]
